### ISSUE TITLE
Cannot run the example

### ISSUE THREAD

**Issue by DzungLeo** [stylehatch/photoset-grid#43]
Hi,
First, thank you for the amazing work. 

I just try your example by downloading the zip file. After extracting and run index.html, here is the result:
![screenshot from 2014-10-09 15 50 03](https://cloud.githubusercontent.com/assets/1518758/4573343/61085624-4f91-11e4-86dd-01a4e959134f.png)

I wonder if there are some scripts not fully loaded.

One more thing, I tried it with my phone gap project, and the result is the same. Could you suggest the solution for this?

Again, thank you!

**Comment by jonathanmoore** [comment]
It sounds like you have something set up wrong. Are you testing it out from a local server?  It's possible that if you just open the index.html file it will not load the resources correctly.
