### ISSUE TITLE
Rails Assets integration

### ISSUE THREAD

**Issue by thefron** [stylehatch/photoset-grid#46]
Hi.
I'd like to install photoset-grid using [rails assets](https://rails-assets.org/), which fetches bower package and builds rails gem.
However rails assets seems to fail in building photoset-grid as version tag in this repository is missing.
Can you please add a tag for the current version?

FYI, you can check the building status of proxied gem here: https://rails-assets.org/components/new

Thanks!

**Comment by jonathanmoore** [comment]
You should be good now! https://github.com/stylehatch/photoset-grid/commit/e362a38a31c05ba86e9bb466a58ab0f2aa522e0d

**Comment by thefron** [comment]
Thanks. It works nicely!
