### ISSUE TITLE
Non-standart photo resolution

### ISSUE THREAD

**Issue by NikitaSmall** [stylehatch/photoset-grid#49]
Good day.
When I try to add a photo with non-standart (non-square) "width-heigth" properties I found myself that I can't do anything with resolution with "height" property.
Am I right that I can manipulate only width param at your module?
P.S. This is my very first issue, so I hope, that you will understand me correctly.
![image](https://cloud.githubusercontent.com/assets/7057358/6400171/dd089fa4-bdff-11e4-9fbb-1c5875538631.png)

**Comment by jonathanmoore** [comment]
Looking at your screenshot it seems like something is not correctly implemented with the plugin.  With the way that it works each row should adjust the height to the shortest image in the row.

The top row in your screenshot should have the two images to the right cropped down:
![image](https://cloud.githubusercontent.com/assets/454095/6408163/abd0ce8a-be03-11e4-9c0e-3ab4daaae8df.png)

Can you post this online somewhere?

**Comment by NikitaSmall** [comment]
I will pudlish this work in few days at heroku.
But for now you can go to my repository: https://github.com/NikitaSmall/route66.git
If you will see code: it is situated at /app/views/landing folder.
Plugin is situated at the assets folder.
Thanks for the fast reply!

**Comment by jonathanmoore** [comment]
In order to be able to determine that it's an issue with the Photoset Grip plugin can you set up a bare bones implementation to recreate the issue at http://codepen.io/

**Comment by NikitaSmall** [comment]
This is a little demostration:
http://codepen.io/NikitaSmall/pen/rarVBw

Thanks for your help, but I desolved this issue. It looks like I did some wrong settings. But for now all is very fine. Thanks again!
