### ISSUE TITLE
Why "Adding a buffer to shave off a few pixels in height"?

### ISSUE THREAD

**Issue by kolingua** [stylehatch/photoset-grid#50]
Which is the reason for shaving 2,5% of height? An image may have an important detail there, so I would like to know if you have a good reason for doing so, as I cannot guess one.

**Comment by jonathanmoore** [comment]
Originally the plugin was created for Tumblr where the image sizes and dimensions are highly inconsistent for Photoset posts. Also, in that context almost every photoset grid is cropped vertically to some degree.  In this case the buffer is essential to a uniform grid.
