### ISSUE TITLE
Optional adding a caption to the images in the grid. 

### ISSUE THREAD

**Issue by neoone256** [stylehatch/photoset-grid#52]
Hello this is more an enhancement than an issue. I would like to know if that is possible to have a text wrapped by span tags or something to give some text to the images. It would be nice if the text is not over the image but at the bottom so that you can put a title and an small description. Of course all images should have that... Thats why it would be optional.

I've been trying to do it but with no luck.

Thanks for the plugin it is very nice!

**Comment by butchewing** [comment]
+1

**Comment by BrockleyJohn** [comment]
Basic captions are a very easy change, see https://github.com/stylehatch/photoset-grid/compare/master...BrockleyJohn:titles

...then just add a title attribute to the image and it's passed through to the link. Colorbox adds it as a caption

**Comment by jonathanmoore** [comment]
:+1: merged.  Thanks @BrockleyJohn
