### ISSUE TITLE
Safari zero row height bug

### ISSUE THREAD

**Issue by NazarkinRoman** [stylehatch/photoset-grid#56]
Tested on safari 7.1.7(mac) and iOS safari(8.2, 7.0). All `.photoset-row` getting 0px height, so grid is invisible. 

Error some here:
```
// Get the row height from the calculated/real height/width of the shortest image
var rowHeight = ( $shortestImg.attr('height') * parseInt($shortestImg.css('width'), 10) ) / $shortestImg.attr('width');

// Adding a buffer to shave off a few pixels in height
var bufferHeight = Math.floor(rowHeight * 0.025);
$(this).height( rowHeight - bufferHeight );
```

If completely remove last line from this snippet - all seems to be working well.

**Comment by jonathanmoore** [comment]
Currently there aren't any reproducible issues in Safari 7 or even as far back as Safari 4.  If you're running into an issue where the `.photoset-row` is getting set to 0px then it is probably related to an implementation issues on your end.

If you could publish a simplified demonstration of the issue to http://codepin.io I'm happy to look into it.

![screen shot 2015-07-02 at 8 53 13 pm](https://cloud.githubusercontent.com/assets/454095/8492314/c8e258b6-20fc-11e5-818c-274a72ec9152.png)

![screen shot 2015-07-02 at 8 55 24 pm](https://cloud.githubusercontent.com/assets/454095/8492317/d56ea710-20fc-11e5-9fa6-6fea40c33313.png)
