### ISSUE TITLE
Photosets don't show up when using Safari 8.0.7

### ISSUE THREAD

**Issue by pablaber** [stylehatch/photoset-grid#57]
When using safari, photosets don't show up because their height is being set to 0px in `resizePhotosetGrid()` in `jquery.photoset-grid.js`

I've looked into it and found that line 248: `var $shortestImg = $(this).find('img:eq(0)');` returns something different in Safari and therefore the `$shortestImg.css('width'), 10)` will return 0 and set the whole `rowHeight` to 0, which in turn sets `bufferHeight` to 0, and therefore `$(this).height( rowHeight - bufferHeight );` sets the height to 0.

**Comment by pablaber** [comment]
I fixed the issue by changing line 288 from `resizePhotosetGrid();` to
``` $(window).load(function() {
            resizePhotosetGrid();
          }); ```

**Comment by droplab** [comment]
Yeah, the images all need to be loaded otherwise the plugin can't correctly calculate widths and heights. You could use the imagesLoaded() plugin for this problem as well. Cheers
