### ISSUE TITLE
Problem with plugin on initial load, works fine after subtle resize

### ISSUE THREAD

**Issue by aligajani** [stylehatch/photoset-grid#58]
Hey, great plugin man. The plugin is being used in its normal mode, and this GIF demonstrates the issue.

http://i.imgur.com/hkgFNO2.gif

Basically, when the page loads, the photos are not expanded, rather stacked weirdly.

A subtle resize of the browser window fixes that. 

Any ideas what's happening? Quite frustrating.

**Comment by jonathanmoore** [comment]
That certainly isn't an issue we've seen on the 10,000s of blogs currently using the plugin for Tumblr's Photoset feature.  Could you reproduce the same issue on codepen.io?

**Comment by aligajani** [comment]
I fixed it Mr. Moore. Was a spinner playing up.
