### ISSUE TITLE
Clicking third image opens up first image?

### ISSUE THREAD

**Issue by aligajani** [stylehatch/photoset-grid#59]
Why is this happening Mr. Moore. If I have 3 images in a row, and I click the third one, it opens the first one. I see that it is wrapping the link on the entire div row instead of the individual image. How do I fix this?

**Comment by jonathanmoore** [comment]
It sounds like something is off quite a bit in your implementation.

See #60 

> Without a link to an isolated demo where you have recreated the issue I wouldn't know how to help you out. Here is a helpful resource on why providing an isolated issue demo (with a link) is helpful: https://github.com/desandro/issues-agreement/#isolate-the-issue
