### ISSUE TITLE
Why are some images like this, like see the second one?

### ISSUE THREAD

**Issue by aligajani** [stylehatch/photoset-grid#60]
http://d.pr/i/6YRL

**Comment by jonathanmoore** [comment]
I have no clue :sunglasses:

Without a link to an isolated demo where you have recreated the issue I wouldn't know how to help you out.  Here is a helpful resource on why providing an isolated issue demo (with a link) is helpful: https://github.com/desandro/issues-agreement/#isolate-the-issue
