### ISSUE TITLE
Algorithm for randomly generating layouts based on N number of images?

### ISSUE THREAD

**Issue by aligajani** [stylehatch/photoset-grid#61]

**Comment by jonathanmoore** [comment]
The photoset grid was designed specifically as a responsive solution for Tumblr's photoset feature.  Extending it beyond that is outside of the goals of the plugin for now.

It's a good idea though!

**Comment by aligajani** [comment]
Technically if I have 100 images, I have to specify the layout instructions like 5456745 etc..I think I can probably write a simply algorithm to generate that in a range. A good start.
