### ISSUE TITLE
Limit to data layout amount 

### ISSUE THREAD

**Issue by michaelbeil** [stylehatch/photoset-grid#64]
We noticed that there could be a bug when using a value in the data layout that exceeds 19. At 20 numbers in a row, the field defaults to this:

What I have at 19:
212122212122212121

What I have at 20:
2121222121222121212

When I save:
9223372036854775807

This could just be a quirk, or we could simply stay below 19 numbers in the data layout.

Thoughts?

**Comment by jonathanmoore** [comment]
I'm having a bit of a difficult time understanding exactly the issue you're running into.  When you're referring to "saving" are you talking about a web app that is generating the layout data string?

Also, I'm not following your strings for "at 19" and "at 20".  The first one should be 18 numbers long generating a total of 18 rows to the grid.

For `212122212122212121`, the first row would have 2 columns, second 1 column, third 2 columns, fourth 1 column, fifth 2 columns, etc.

The difference between `212122212122212121` and `2121222121222121212` should only be an additional row at the bottom with two columns.

There shouldn't be a limit to the layout amount, although if you have a ton of images it could start to become a performance issue.

**Comment by michaelbeil** [comment]
I am thinking that it is a freak issue that is happening in our WordPress plugin Aesop Story Engine which uses your library for our photoset galleries. 

Perhaps we need to reconfigure our generator, but we have never run into anyone using the gallery with this many photo rows. 

When I attempt a similar gallery insertion on my end, I am not seeing the issue every time. I was only able to replicate it once, so I am just going to close this as it does not seem to be totally valid. 

Thanks for your help @jonathanmoore!
