### ISSUE TITLE
Incorrect layout on various heights

### ISSUE THREAD

**Issue by alialo** [stylehatch/photoset-grid#67]
I'm having a problem regarding layouts with images of different heights in a row - sometimes the grid is correctly laid out, other times the row height isn't calculated from the smallest image in that row. Please see the following pen:

http://codepen.io/anon/pen/QydvpB#0

I can't seem to find a reason why it randomly breaks - for example, the third image in grid one will break when its height is set to anything lower than the current 125px (try 124), but it works when you set its height between 12 - 25px. Set it to 11px and it breaks again.

**Comment by jonathanmoore** [comment]
Fixed
