### ISSUE TITLE
Gutter not working between rows

### ISSUE THREAD

**Issue by cfjedimaster** [stylehatch/photoset-grid#70]
For some reason I'm only getting a gutter between columns, now rows. Example:

![image](https://cloud.githubusercontent.com/assets/393660/14022195/c7f164c0-f1ac-11e5-89e7-924df1961d12.png)

Here is the code I'm using:

    $('#results').html(s).photosetGrid({
      gutter:'15px',
      onComplete:function() {
        $('#results').show();
      }
    });

**Comment by cfjedimaster** [comment]
Ok, so this is odd. In another test, I get gutters between rows, and not columns:

![image](https://cloud.githubusercontent.com/assets/393660/14022275/1690fd7a-f1ad-11e5-93cc-1d6a65b262b1.png)

**Comment by jonathanmoore** [comment]
This should be fixed with #72
