### ISSUE TITLE
Different grid 

### ISSUE THREAD

**Issue by kamov** [stylehatch/photoset-grid#71]
Hi,
is possible to setup a new grid system?

I would like something like below:
![screen shot 2016-03-28 at 10 45 20](https://cloud.githubusercontent.com/assets/2345000/14074838/539e254c-f4d4-11e5-8ab1-7f6936b460f9.png)

**Comment by jonathanmoore** [comment]
It's a great idea, but not something that would be handled by photoset grid since it was designed specifically for a solution to Tumblr's unique feature.
